update ci

diff --git a/.github/workflows/create-rlease.yml b/.github/workflows/create-rlease.yml
--- a/.github/workflows/create-rlease.yml
+++ b/.github/workflows/create-rlease.yml
@@ -13,14 +13,29 @@ on:
           - minor
           - patch
 
+env:
+  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  GH_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
+  GH_USER: 'github-actions[bot]'
+
 jobs:
   bump-version:
     runs-on: ubuntu-latest
+    if: ${{ github.ref == 'refs/heads/main' }}
     env:
       VERSION_TYPE: ${{ github.event.inputs.version-type }}
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
+
+      - name: Install pnpm
+        uses: pnpm/action-setup@v4.0.0
+
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20.x'
+          cache: 'pnpm'
 
       - name: Display selected version type
         run: echo "Selected version type-> ${VERSION_TYPE}"
@@ -31,14 +46,56 @@ jobs:
           case "${VERSION_TYPE}" in
             major)
               echo "Bumping major version"
-              # Add logic to bump major version
+              pnpm version major --no-commit-hooks --no-git-tag-version
               ;;
             minor)
               echo "Bumping minor version"
-              # Add logic to bump minor version
+              pnpm version minor --no-commit-hooks --no-git-tag-version
               ;;
             patch)
               echo "Bumping patch version"
-              # Add logic to bump patch version
+              pnpm version minor --no-commit-hooks --no-git-tag-version
               ;;
           esac
+
+      - name: Parse package.json
+        id: identify-version
+        run: |
+          APP_VERSION="$(cat ./package.json |jq .version|sed -e 's/"//g'| head -n1)"
+          if [ ! -n "${APP_VERSION}" ]; then
+            exit 255
+          fi
+          echo "Detected the version: ${APP_VERSION}"
+          echo "app-version=${APP_VERSION}" >>"${GITHUB_OUTPUT}"
+          echo "app-version-text=v${APP_VERSION}" >>"${GITHUB_OUTPUT}"
+    
+
+      - name: Check if there are any changes
+        run: |
+          git add -N .
+          if git diff --exit-code --quiet; then
+            echo "No changes detected."
+            echo "ERROR: could not update the package.json"
+            exit 1
+          else
+            echo "Changes detected."
+            # git add .
+            # git commit -m "chore: update version of package.json" -m "[AUTO]"
+            # RESULT="is-changed=1"
+          fi
+          # echo "${RESULT}">>"${GITHUB_OUTPUT}"
+          # echo "${RESULT}"
+
+      - name: Checkout new repository
+        env:
+          APP_VERSION: ${{steps.identify-version.outputs.app-version}}
+          APP_VERSION_TEXT: ${{steps.identify-version.outputs.app-version-text}}
+        run: |
+          BRANCH_NAME="release/${APP_VERSION_TEXT}"
+          git checkout -b "${BRANCH_NAME}"
+          git add .
+          git commit -m "chore: update version of package.json" -m "[AUTO]"
+          git push -u origin "${BRANCH_NAME}"
+          gh pr create --title "chore(release): ${APP_VERSION_TEXT}" --body "**Preparations for ${APP_VERSION_TEXT}**"
+
+
